### ISSUE TITLE
Unicode error in commentjson v0.7.2 in python2.7 environment

### ISSUE THREAD

**Issue by nazrulworld** [vaidik/commentjson#23]
After upgrading commentjson to `v0.7.2` getting bellows problem, you know codebase is same.

```
with io.open("some json file path", "r", encoding="utf-8") as fp:
    commentjson.loads(fp.read())
```
```
File "/home/nazrul/.cache/buildout/eggs/commentjson-0.7.2-py2.7.egg/commentjson/commentjson.py", line 73, in loads
    text = six.text_type(text, 'utf-8')
TypeError: decoding Unicode is not supported
```

**Comment by vaidik** [comment]
If you are using python 2.7, `commentjson` would automatically handle encoding for you. You probably don't need to do this.

Try this:

```py
with open("some json file path", "r") as fp:
    commentjson.loads(fp.read())
```

**Comment by blackchoey** [comment]
I have similar issue. Now I need to `commentjson.loads(json_content.encode('ascii'))` in python 2.7 and `commentjson.loads(json_content)` in python 3.
Prior to v.0.7.2, `commentjson.loads(json_content)` works with both python 2.7 and python 3

**Comment by vaidik** [comment]
@blackchoey I see. Thanks for reporting this. I might have broken a more straight foward use-case in order to handle another use-case. I think this might need a revert in commentjson. I want to be more careful this time in the fix I make. so this might take a while for me to release because I work only weekends on commentjson.

I was looking at the PR referenced in your project. While I fix this, why dont you pin the [requirements.txt](https://github.com/Azure/iotedgedev/blob/master/requirements.txt#L16) file with an older version of commentjson or the latest version according to which you have patched your code? That will ensure that when I make a release, your code doesnt break

**Comment by vaidik** [comment]
@nazrulworld your issue is valid as well. Will put out a fix soon

**Comment by blackchoey** [comment]
@vaidik Thanks for the update, we also want support for non-ascii characters. Do you mean there might be some breaking changes in the new version? We will specify the version of commentjson to make sure the code doesn't break.

**Comment by vaidik** [comment]
@blackchoey yeah that's what I meant. One of my design goals for commentjson was to have its interface completely consistent with the `json` package in the stdlib. It seems that I broke that in 0.7.2 while rushing to make a fix, which broke things for you. In order to fix that, I am going to have to make some breaking changes, but for a better experience.

**Comment by vaidik** [comment]
@nazrulworld @blackchoey can you install using this (#27) branch locally and try to see if your issues are resolved?

What I have done is changed commentjson to use some of the implementation of handling unicode the way it is in python 3 and now all test cases of json package for handling unicode are also being run in commentjson (see this - https://github.com/vaidik/commentjson/pull/27/files#diff-3af1afda709118dfc0256eb374690399). This just ensures that commentjson is handling unicode exactly like json.

Does this solve the problem for you guys? If it does, then I will make a release.

@blackchoey this will be backward incompatible from the previous version.

**Comment by vaidik** [comment]
@nazrulworld @blackchoey can you guys please review this? Does this change solve for what you are looking for?

**Comment by vaidik** [comment]
Hey @nazrulworld @blackchoey 

Can you guys take a look please? I am quite certain that this would work but I just thought it would be nice to get your feedback too.

**Comment by nazrulworld** [comment]
@vaidik I am sorry, was too busy, will let you know as soon possible.

**Comment by vaidik** [comment]
@nazrulworld i absolutely understand. Thanks so much for responding and taking a look at this. Appreciate your support

**Comment by nazrulworld** [comment]
@vaidik seems the same problem! what I did 
1. took the master branch 
```
with io.open("DIAPROFIL_HCP_ITEM_NOTES.json", "r", encoding="utf-8") as fp:
...     commentjson.loads(fp.read())
```

If my test procedure is not wrong, I suggest you create a JSON file with some danish words.

like 
```
{
                      "url": "text",
                      "valueString": "ID for spørgeskemabesvarelse"
                    }
```

**Comment by vaidik** [comment]
@nazrulworld fixes are not in master. they are in `fix-unicode-handling`. You can also refer to the changes in this PR (#27).

**Comment by nazrulworld** [comment]
@vaidik thanks and sorry for any confusion :)
I saw everything is working perfectly, happy coding

**Comment by vaidik** [comment]
Thanks a lot @nazrulworld for testing that for me. I have added Danish and Bengali characters in the test suite as well

**Comment by vaidik** [comment]
@blackchoey I am merging this to master and making a release. This is probably going to be backward incompatible, so please please watch out.

**Comment by vaidik** [comment]
Made a release
